//LEVEL 1
var mazeContent1 = [
//row1
[LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_ONLY, TOP_BOTTOM,
 TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_TOP, TOP_ONLY,
 TOP_ONLY, TOP_ONLY, TOP_ONLY, TOP_ONLY, TOP_ONLY,
 TOP_ONLY, RIGHT_TOP],
//row2
[LEFT_RIGHT, BOTTOM_LEFT_TOP, RIGHT_TOP, LEFT_RIGHT, LEFT_TOP,
 TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_BOTTOM, BOTTOM_ONLY,
 BOTTOM_ONLY, BOTTOM_ONLY, BOTTOM_ONLY, BOTTOM_ONLY, EMPTY_GRID,
 EMPTY_GRID, RIGHT_ONLY],
//row3
[LEFT_BOTTOM, RIGHT_TOP, LEFT_RIGHT, LEFT_RIGHT, LEFT_RIGHT,
 BOTTOM_LEFT_TOP, TOP_BOTTOM, EMPTY_GRID, TOP_BOTTOM, TOP_BOTTOM,
 TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_ONLY,
 EMPTY_GRID, RIGHT_ONLY],
//row4
[CLOSED_GRID, LEFT_RIGHT, LEFT_RIGHT, LEFT_RIGHT, LEFT_BOTTOM,
 TOP_BOTTOM, RIGHT_TOP, LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM,
 TOP_BOTTOM, TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_ONLY,
 EMPTY_GRID, RIGHT_ONLY],
//row5
[LEFT_TOP, RIGHT_BOTTOM, LEFT_RIGHT, LEFT_BOTTOM, TOP_ONLY,
 TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM,
 TOP_BOTTOM, TOP_ONLY, TOP_BOTTOM, RIGHT_BOTTOM, LEFT_ONLY,
 EMPTY_GRID, RIGHT_ONLY],
//row6
[LEFT_RIGHT, BOTTOM_LEFT_TOP, BOTTOM_ONLY, TOP_RIGHT_BOTTOM, LEFT_RIGHT,
 BOTTOM_LEFT_TOP, RIGHT_BOTTOM, LEFT_RIGHT, LEFT_TOP, TOP_BOTTOM,
 RIGHT_TOP, LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, BOTTOM_ONLY,
 BOTTOM_ONLY, RIGHT_BOTTOM],
//row7
[LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY,
 TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_RIGHT, LEFT_TOP_RIGHT,
 LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
 TOP_BOTTOM, RIGHT_TOP],
//row8
[LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
 TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_RIGHT, LEFT_RIGHT,
 LEFT_RIGHT, LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM,
 TOP_RIGHT_BOTTOM, LEFT_RIGHT],
//row9
[LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_ONLY,
 TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_RIGHT, LEFT_RIGHT,
 LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
 TOP_BOTTOM, RIGHT_ONLY],
//row10
[LEFT_TOP, TOP_ONLY, TOP_ONLY, RIGHT_TOP, LEFT_RIGHT,
 BOTTOM_LEFT_TOP, TOP_RIGHT_BOTTOM, LEFT_RIGHT, RIGHT_BOTTOM_LEFT, LEFT_RIGHT,
 RIGHT_BOTTOM_LEFT, LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM,
 TOP_RIGHT_BOTTOM, LEFT_RIGHT],
//row11
[LEFT_ONLY, EMPTY_GRID, EMPTY_GRID, RIGHT_ONLY, LEFT_ONLY,
 TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY, TOP_ONLY, BOTTOM_ONLY,
 TOP_BOTTOM, BOTTOM_ONLY, TOP_ONLY, TOP_BOTTOM, TOP_BOTTOM,
 TOP_BOTTOM, RIGHT_ONLY],
//row12
[LEFT_ONLY, EMPTY_GRID, EMPTY_GRID, RIGHT_ONLY, LEFT_RIGHT,
 BOTTOM_LEFT_TOP, TOP_BOTTOM, RIGHT_TOP, LEFT_RIGHT, BOTTOM_LEFT_TOP,
 TOP_BOTTOM, RIGHT_TOP, LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM,
 RIGHT_TOP, LEFT_RIGHT],
//row13
[LEFT_ONLY, EMPTY_GRID, EMPTY_GRID, RIGHT_ONLY, LEFT_ONLY,
 TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM,
 TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM, RIGHT_TOP,
 LEFT_RIGHT, LEFT_RIGHT],
//row14
[LEFT_ONLY, EMPTY_GRID, EMPTY_GRID, RIGHT_ONLY, LEFT_RIGHT,
 LEFT_TOP, TOP_BOTTOM, RIGHT_BOTTOM, LEFT_RIGHT, BOTTOM_LEFT_TOP,
 TOP_BOTTOM, RIGHT_ONLY, LEFT_RIGHT, LEFT_TOP_RIGHT, LEFT_RIGHT,
 LEFT_RIGHT, LEFT_RIGHT],
//row15
[LEFT_ONLY, EMPTY_GRID, EMPTY_GRID, RIGHT_ONLY, LEFT_RIGHT,
 LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, EMPTY_GRID, TOP_BOTTOM,
 TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_RIGHT, LEFT_RIGHT, LEFT_RIGHT,
 LEFT_RIGHT, LEFT_RIGHT],
//row16
[LEFT_ONLY, EMPTY_GRID, EMPTY_GRID, RIGHT_ONLY, LEFT_RIGHT,
 LEFT_BOTTOM, TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, BOTTOM_LEFT_TOP,
 TOP_BOTTOM, RIGHT_BOTTOM, LEFT_RIGHT, LEFT_RIGHT, LEFT_RIGHT,
 RIGHT_BOTTOM_LEFT, LEFT_RIGHT],
//row17
[LEFT_BOTTOM, BOTTOM_ONLY, BOTTOM_ONLY, RIGHT_BOTTOM, LEFT_BOTTOM,
 TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY, TOP_BOTTOM,
 TOP_BOTTOM, TOP_BOTTOM, RIGHT_BOTTOM, RIGHT_BOTTOM_LEFT, LEFT_BOTTOM,
 TOP_BOTTOM, RIGHT_BOTTOM]
];


// LEVEL 2
var mazeContent2 = [
//row1
[LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_ONLY,
  TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_TOP,
  TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_ONLY, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_TOP],
//row2
[LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT,
 BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, LEFT_RIGHT,
 BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_RIGHT_BOTTOM, LEFT_RIGHT, BOTTOM_LEFT_TOP,
 TOP_RIGHT_BOTTOM, LEFT_RIGHT],
//row3
[LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, EMPTY_GRID,
 TOP_ONLY, TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY, BOTTOM_ONLY,
 TOP_BOTTOM, TOP_BOTTOM, TOP_ONLY, EMPTY_GRID, TOP_BOTTOM,
 TOP_BOTTOM, RIGHT_ONLY],
//row4
[LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY,
 LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_TOP,
 TOP_BOTTOM, TOP_BOTTOM, RIGHT_BOTTOM, LEFT_ONLY, TOP_BOTTOM,
 TOP_BOTTOM, RIGHT_BOTTOM],
//row5
[LEFT_TOP, TOP_ONLY, TOP_ONLY, RIGHT_TOP, LEFT_RIGHT,
 LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_ONLY,
 TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_RIGHT, LEFT_TOP,
 TOP_ONLY, RIGHT_TOP],
//row6
[LEFT_BOTTOM, BOTTOM_ONLY, BOTTOM_ONLY, RIGHT_BOTTOM, LEFT_RIGHT,
  LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_ONLY,
  TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_RIGHT, LEFT_BOTTOM,
  BOTTOM_ONLY, RIGHT_BOTTOM],
//row7
[LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY,
  RIGHT_ONLY, LEFT_TOP, TOP_RIGHT_BOTTOM, LEFT_ONLY, RIGHT_ONLY,
  BOTTOM_LEFT_TOP, RIGHT_TOP, LEFT_ONLY, BOTTOM_ONLY, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_TOP],
//row8
[LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  RIGHT_ONLY, LEFT_RIGHT, LEFT_TOP, EMPTY_GRID, EMPTY_GRID,
  RIGHT_TOP, LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_BOTTOM],
//row9
[LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  RIGHT_ONLY, LEFT_RIGHT, LEFT_BOTTOM, BOTTOM_ONLY, BOTTOM_ONLY,
  RIGHT_BOTTOM, LEFT_RIGHT, LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, TOP_RIGHT_BOTTOM],
//row10
[LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_RIGHT_BOTTOM,
  LEFT_RIGHT, LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_BOTTOM, LEFT_RIGHT, BOTTOM_LEFT_TOP, TOP_BOTTOM,
  TOP_BOTTOM, TOP_RIGHT_BOTTOM],
//row11
[LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  EMPTY_GRID, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, TOP_BOTTOM, EMPTY_GRID, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, TOP_RIGHT_BOTTOM],
//row12
[LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  EMPTY_GRID, TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_TOP,
  TOP_BOTTOM, TOP_BOTTOM, EMPTY_GRID, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_TOP],
//row13
[LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_ONLY,
  BOTTOM_ONLY, TOP_BOTTOM, TOP_ONLY, RIGHT_BOTTOM, LEFT_BOTTOM,
  TOP_ONLY, TOP_BOTTOM, BOTTOM_ONLY, TOP_ONLY, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_BOTTOM],
//row14
[LEFT_TOP, TOP_ONLY, TOP_ONLY, RIGHT_TOP, LEFT_ONLY,
  TOP_ONLY, TOP_BOTTOM, BOTTOM_ONLY, RIGHT_TOP, LEFT_TOP,
  BOTTOM_ONLY, TOP_BOTTOM, TOP_ONLY, RIGHT_ONLY, LEFT_TOP,
  TOP_ONLY, RIGHT_TOP],
//row15
[LEFT_BOTTOM, TOP_ONLY, TOP_ONLY, RIGHT_TOP, RIGHT_ONLY,
  LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY, BOTTOM_ONLY,
  TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_RIGHT, LEFT_BOTTOM,
  BOTTOM_ONLY, RIGHT_BOTTOM],
//row16
[LEFT_TOP, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, RIGHT_BOTTOM,
  LEFT_ONLY, TOP_BOTTOM, TOP_BOTTOM, RIGHT_TOP, LEFT_TOP,
  TOP_BOTTOM, TOP_BOTTOM, RIGHT_ONLY, LEFT_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_TOP],
//row17
[LEFT_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM, TOP_BOTTOM,
  BOTTOM_ONLY, TOP_BOTTOM, TOP_BOTTOM, RIGHT_BOTTOM, LEFT_BOTTOM,
  TOP_BOTTOM, TOP_BOTTOM, BOTTOM_ONLY, TOP_BOTTOM, TOP_BOTTOM,
  TOP_BOTTOM, RIGHT_BOTTOM]
];
